language: node_js
sudo: false
node_js:
- '5.0'
- 'stable'
branches:
  except:
  - /^v[0-9\.]+/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  matrix:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
    - CXX=g++-4.8
    - secure: W+4D92YMMC5C/TIlFAlQm67OiOepljFeI5eNVbBGd4z7lWGSEE4aeTfwVs1qwN4tFz7LXSLXoy8hgTsb8VU0LZXgm/fzvWz5cPN9Rj2sJWbzboyHI+cw1AXevT/UkpnUqSY5g96+gh62hjClPQomxQZCxcuzGWtlb6VLfDj3r4X1n739htjnFSAAr+DVi3Jl+TkEMfb0nxoT6u/l8uXtyqeIrA5spnLlZyoWQoO3hYJxqjFLUp90YsCCukp1JYvVNGZeA3zjDIgc0JKM7pBpxrPMCPd+v5QEC9PiuJXdW6it+6O52kOXArX+NfTfjeFRhTlFmcfoEYZdNIFb8iD9evZBtON+E+51Ecv2noCfDKj22WCs15ALva8q83fkzdxTw9BOoM+fORYPyOrsN28oj4Z1UsvKadiUwI6qGIITmJl1ZuJiK0SjnxMDc8A8CSl6q/11J5NuzT2NQLUUSCH0224bxR4OfP8U198xI/GXWkCKmF6hwxsl9kNgnbKWdC0pDfiEgEZ+KsQrI8naNViLmFRYE/SGJexoo6J6/nkF1Z+2VSoBHvpM/qAXSUdw1CYnPFfXCFyXe07nB8XqjgKNqgGash6S4XVkXWA2hjz3GtiXLPXZqPV7ssIPQx+JV8KGRr3dL/gRnpCH49lNB6R9rPm+xlCEqccDcpDh10popH8=
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
install:
- npm install
- bower install
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
script:
- ember try:one $EMBER_TRY_SCENARIO --- ember test
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: kOUhZ/JbccEhA7JKlxaW8EhyDw6zIXzNgT13861tfz3EsWsGk4OKxGvJI9metrvfFSX2gbghIwYsq4s3/5EecLU44Cm1a2SVL92qZvFYqfHsdtStCiSVPV9BewDjhRTs4GIctRowln+SP3S9p2/DBJymR2tupjfLS5WaeCmJu9YU3qtu7cVHWoqJuX1udjlzaG95VdQ7YlWKubDGAF8gRtrIG4QkYTNSGY1ivVKOn59S/IW+rHudA0kF6doGYk3vfMN3TTzoxuiIi1eIZ8211Q8uedJqku0rj4i/j5GQIzoeDfW21iD8bl7wHFnvKFmssP915jnD5X+bRvBiJ/Ore0d+PrjrIhZzEPilN1eftfg8Cu3EzBOBnf3bV80wD1p8bXNZj2Ip3gycOFwo2YnRr2xyR1R7wDt+J6XVNyJNVuD+u1LWk+Uxd1krGJtitB1mz95gNKTQveQ6tK/M3K4zv7JSoz9BP3wbXs0bpTdq8ETPGSBpTUgVTSetjJ3nvTkuctOtOeHOZjxP9XN4Gzu1c3sB3zSOX5squwVmIvDfSO6huF/6ESJxzLheQzveW1COQSv9S/Pt5ZO/jrXyBlrX4DhlRl2GbF/mxiNVB4zlCrvzeYIqfOHjPQRRV4vsFp3VbiZ4LI/lI4m7RWuHxmOZclg3BjNwZTsunGiZWdXIyq8=
  on:
    branch: master
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: 'stable'
    tags: false
after_deploy:
- .travis/publish-gh-pages.sh
